#!/usr/bin/env python3
"""Generate bounded English short-word bigram/trigram priors from Tatoeba."""

import argparse
import bz2
from collections import Counter
import hashlib
import math
from pathlib import Path
import re
import tempfile
import urllib.request

SOURCE_URL = "https://downloads.tatoeba.org/exports/per_language/eng/eng_sentences.tsv.bz2"
SOURCE_SHA256 = "34fc76cc177ca65b56cb3b966a2b8f33efd8a1b0551eb855f31b5ab940d05e60"
ROWS_PER_ORDER = 2048
WORD_RE = re.compile(r"[A-Za-z]+(?:'[A-Za-z]+)?")
# Tatoeba's English examples heavily reuse these fictional names. Excluding
# named sentences keeps the model conversational without teaching names.
RECURRING_NAMES = {
    "Alice", "Ann", "Bill", "Bob", "Jack", "Jane", "John", "Kate",
    "Mary", "Mike", "Sam", "Tom",
}
OUTPUTS = (
    Path("assets/language_packs/en_AU/next_words.tsv"),
    Path("assets/language_packs/en_GB/next_words.tsv"),
    Path("assets/language_packs/en_US/next_words.tsv"),
)


def fetch_archive(path):
    if not path.exists():
        urllib.request.urlretrieve(SOURCE_URL, path)
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    if digest != SOURCE_SHA256:
        raise SystemExit(f"Tatoeba snapshot SHA-256 mismatch: {digest}")


def corpus_counts(path):
    bigrams = Counter()
    trigrams = Counter()
    bigram_contexts = Counter()
    trigram_contexts = Counter()
    with bz2.open(path, "rt", encoding="utf-8", errors="replace") as source:
        for line in source:
            fields = line.rstrip("\n").split("\t", 2)
            if len(fields) != 3:
                continue
            raw = WORD_RE.findall(fields[2])
            if not 2 <= len(raw) <= 30:
                continue
            if raw[0] in RECURRING_NAMES or any(word[:1].isupper() for word in raw[1:]):
                continue
            words = [word.lower() for word in raw]
            for previous, following in zip(words, words[1:]):
                bigram_contexts[previous] += 1
                if 2 <= len(following) <= 3:
                    bigrams[(previous, following)] += 1
            for prior, previous, following in zip(words, words[1:], words[2:]):
                trigram_contexts[(prior, previous)] += 1
                if 2 <= len(following) <= 3:
                    trigrams[(prior, previous, following)] += 1
    return bigrams, trigrams, bigram_contexts, trigram_contexts


def weight(count, context_count):
    confidence = count / context_count
    return max(8, min(15, round(7 + math.log2(count) / 2 + 3 * confidence)))


def selected_bigrams(counts, contexts):
    eligible = [pair for pair, count in counts.items() if count >= 30]
    by_count = sorted(
        eligible, key=lambda pair: (counts[pair], pair), reverse=True)
    by_confidence = sorted(
        eligible,
        key=lambda pair: (
            counts[pair] / contexts[pair[0]], counts[pair], pair),
        reverse=True,
    )
    selected = set(by_count[:1536])
    for pair in by_confidence:
        if len(selected) >= ROWS_PER_ORDER:
            break
        selected.add(pair)
    if len(selected) != ROWS_PER_ORDER:
        raise SystemExit("Bigram selection did not reach its fixed bound")
    return [(pair, weight(counts[pair], contexts[pair[0]]))
            for pair in sorted(selected)]


def selected_trigrams(counts, contexts):
    ranked = sorted(
        counts,
        key=lambda triple: (
            counts[triple] * counts[triple] / contexts[triple[:2]],
            counts[triple],
            triple,
        ),
        reverse=True,
    )[:ROWS_PER_ORDER]
    return [(triple, weight(counts[triple], contexts[triple[:2]]))
            for triple in sorted(ranked)]


def render(bigrams, trigrams):
    rows = [
        "# Tatoeba English short-word priors; generated by generate_short_word_ngrams.py",
        "# previous<TAB>next<TAB>weight or prior<TAB>previous<TAB>next<TAB>weight",
    ]
    rows.extend(f"{a}\t{b}\t{value}" for (a, b), value in bigrams)
    rows.extend(f"{a}\t{b}\t{c}\t{value}" for (a, b, c), value in trigrams)
    return "\n".join(rows) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--archive", type=Path)
    args = parser.parse_args()
    temporary = None
    archive = args.archive
    if archive is None:
        temporary = tempfile.TemporaryDirectory()
        archive = Path(temporary.name) / "eng_sentences.tsv.bz2"
    fetch_archive(archive)
    counts = corpus_counts(archive)
    content = render(selected_bigrams(counts[0], counts[2]),
                     selected_trigrams(counts[1], counts[3]))
    for output in OUTPUTS:
        output.write_text(content, encoding="utf-8")
    if temporary is not None:
        temporary.cleanup()


if __name__ == "__main__":
    main()
